name: test

on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: Run Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true

      - name: luajit
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "luajit"

      - name: luarocks
        uses: leafo/gh-actions-luarocks@v4

      - name: test setup
        run: make test_setup

      - name: run tests
        run: make coverage

      - name: Upload coverage report
        uses: 5monkeys/cobertura-action@v13
        with:
          path: coverage.xml
          minimum_coverage: 100
